### ISSUE TITLE
Not dealing with duplicate names well

### ISSUE THREAD

**Issue by gshively11** [godaddy/kibana4-backup#14]
Kibana does not enforce unique names for searches/dashboards/etc.  It causes weird behavior in the backup process.  We need to ensure that names are unique for all saved assets.

**Comment by gshively11** [comment]
Discovered in https://github.com/godaddy/kibana4-backup/issues/10

**Comment by bobcat0070** [comment]
Not sure if you want to explore this option, but could be worth porting to leverage https://github.com/taskrabbit/elasticsearch-dump ... this seemingly deals with duplicates without any problems.

**Comment by gshively11** [comment]
@bobcat0070 It's a good suggestion, we are actually already leveraging it :smile:

However, we are taking the data pulled by elasticsearch-dump and splitting it into separate files, so that they can be modified/deployed separately.  That introduces this issues, because if two documents in the index have the same _id, they overwrite each other.

**Comment by bobcat0070** [comment]
Gotcha, so simply naming based on _type + _id would fix it.

**Comment by gshively11** [comment]
Fixed in https://github.com/godaddy/kibana4-backup/commit/bec62a53bc84d8d0c33ad85ec8c7a12102adcf92
