### ISSUE TITLE
Deploy Specific Revision Flag

### ISSUE THREAD

**Issue by bobcat0070** [godaddy/kibana4-backup#15]
Currently it’s manual to restore a version because you would need to grab the files from that revision and drop them in the deploy folder.

It would be nice to have a “deploy this revision” argument that could be used in those situations.

**Comment by gshively11** [comment]
solid recommendation, will try to get to it in the near future

**Comment by gshively11** [comment]
completed in https://github.com/godaddy/kibana4-backup/pull/16

**Comment by couponpitara** [comment]
I always recommend this blog for latest movements in worlds which they matters.
<a href="http://www.couponpitara.com/offers/godaddy/"> Godaddy Coupons </a>
