### ISSUE TITLE
Great!

### ISSUE THREAD

**Issue by mkliu** [godaddy/kibana4-backup#4]
This is great, exactly what I've been looking for! Thanks!
A couple of feedbacks
1. My git URL has a space, it's encoded as %20, but the commander is parsing that to just 0
2. Can you make it a bit more windows friendly? For example:
    a. if you use pattern names as file names, file names with * cannot be created
    b. I know it's not from you, but ES Dump is looking for ":" to decide if it's ElasticSearch protocal, but windows uses C:, which makes it think it's ElasticSearch protocal.

**Comment by gshively11** [comment]
Thanks for the feedback @mkliu!  I'm looking into these issues now, hopefully I'll have fixes soonish.

**Comment by gshively11** [comment]
@mkliu Can you see if 0.2.2 fixes some of your issues?  The ESDump issue is still open, but the filename stuff should work now.

**Comment by mkliu** [comment]
thanks! The windows file name is working, though haven't tried deploying that to another cluster yet.
For the ESDump, I hacked their code where they check the protocol for now.

**Comment by mkliu** [comment]
actually, the %20 issue turned out to be windows .bat file is treating % as special char. The fix is to make it %%20.

However, another thing i have to tweak myself is this
     .option('-e, --environment <env>', 'the environment you want to target', 'default')

There was the alphanumeric validator that I had to remove otherwise this variable is returnning me true/false.

**Comment by gshively11** [comment]
Bah, I misunderstood the purpose of that parameter in commander, fixed.  

https://github.com/godaddy/kibana4-backup/releases/tag/v0.3.0

@mkliu let me know if this works for you

**Comment by mkliu** [comment]
yup, those are working now. Btw, if I want to call this in another node.js script, how should I do it? exec as a child process? Coz I have quite some clusterts to backup so want to lump sum that into one script.

**Comment by mkliu** [comment]
i can't seem to pass parameters to the commander process arguments. It'll actually be good if you expose a method where i could pass in the config arguments.

**Comment by gshively11** [comment]
Good suggestion, created https://github.com/godaddy/kibana4-backup/issues/12 to track it.  Will try to get to it today.  Closing this one since the bugs are resolved.

**Comment by gshively11** [comment]
@mkliu let me know if 0.4.0 works for your programatic usage
