### ISSUE TITLE
Make this work with kibana 3 also (edited)

### ISSUE THREAD

**Issue by mkliu** [godaddy/kibana4-backup#6]
I could write something myself but just wondering how are you guys doing that today?

**Comment by gshively11** [comment]
We were doing something dumb.  It shouldn't be too hard to adapt this to work with Kibana 3 though.  I'll create an enhancement issue to track that.  

I think you can store Kibana 3 dashboards as json files in the kibana directory and it can read from there, but don't quote me on that.

**Comment by mkliu** [comment]
yes, the K3 is also just in the index. actually simpler than K4. 
btw, i think you need to expose an optional parameter to allow specifying kibana index name, sometimes people would change it.

**Comment by gshively11** [comment]
https://github.com/godaddy/kibana4-backup/releases/tag/v0.3.0

Verified it pulled down our Kibana 3 dashboards.
