### ISSUE TITLE
Restore kibana throws error

### ISSUE THREAD

**Issue by mkliu** [godaddy/kibana4-backup#9]
I tried to do some restore to make sure it's working. Some works fine but some have problems. Here's the original document. In addition, I would suggest two things:
1. Allow specifying whether I want to restore or backup instead of dynamically specify. It's more reassuring that way.
2. When doing restore, I would hope it goes through everything first, if anything fails, report it out but still continue. Like the case here, it'll be easy to see if there's any other problems

         {
            "_index": ".kibana",
            "_type": "visualization",
            "_id": "Metrics_Status",
            "_score": 1,
            "_source": {
               "title": "Metrics_Status",
               "visState": "{\n  \"type\": \"histogram\",\n  \"params\": {\n    \"shareYAxis\": true,\n    \"addTooltip\": true,\n    \"addLegend\": true,\n    \"isDonut\": false,\n    \"defaultYExtents\": true,\n    \"mode\": \"stacked\"\n  },\n  \"aggs\": [\n    {\n      \"id\": \"1\",\n      \"type\": \"cardinality\",\n      \"schema\": \"metric\",\n      \"params\": {\n        \"field\": \"metric_RequestId\"\n      }\n    },\n    {\n      \"id\": \"2\",\n      \"type\": \"date_histogram\",\n      \"schema\": \"segment\",\n      \"params\": {\n        \"field\": \"timeStamp\",\n        \"interval\": \"auto\",\n        \"min_doc_count\": 1,\n        \"time_zone\": +8\n        \"extended_bounds\": {}\n      }\n    },\n    {\n      \"id\": \"3\",\n      \"type\": \"terms\",\n      \"schema\": \"group\",\n      \"params\": {\n        \"field\": \"metric_RequestStateName.raw\",\n        \"size\": 5,\n        \"order\": \"desc\",\n        \"orderBy\": \"1\"\n      }\n    }\n  ],\n  \"listeners\": {}\n}",
               "description": "",
               "version": 1,
               "kibanaSavedObjectMeta": {
                  "searchSourceJSON": "{\n  \"index\": \"metric-*\",\n  \"query\": {\n    \"query_string\": {\n      \"query\": \"*\",\n      \"analyze_wildcard\": true\n    }\n  },\n  \"filter\": []\n}"
               }
            }
         },

The backed up doc is:

		{"_index":".kibana","_type":"visualization","_id":"Metric_Status","_score":0,"_source":{"title":"Metric_Status","visState":"{\"type\":\"histogram\",\"params\":{\"shareYAxis\":true,\"addTooltip\":true,\"addLegend\":true,\"mode\":\"stacked\",\"defaultYExtents\":false},\"aggs\":[{\"id\":\"1\",\"type\":\"count\",\"schema\":\"metric\",\"params\":{}},{\"id\":\"2\",\"type\":\"date_histogram\",\"schema\":\"segment\",\"params\":{\"field\":\"timeStamp\",\"interval\":\"auto\",\"min_doc_count\":1,\"extended_bounds\":{}}},{\"id\":\"3\",\"type\":\"terms\",\"schema\":\"group\",\"params\":{\"field\":\"Metric_RequestStateName.raw\",\"size\":5,\"order\":\"desc\",\"orderBy\":\"1\"}}],\"listeners\":{}}","description":"","version":1,"kibanaSavedObjectMeta":{"searchSourceJSON":"{\"index\":\"efun-Metric-*\",\"query\":{\"query_string\":{\"query\":\"*\",\"analyze_wildcard\":true}},\"filter\":[]}"}}}\"schema\": \"group\",\n      \"params\": {\n        \"field\": \"Metric_RequestStateName.raw\",\n        \"size\": 5,\n        \"order\": \"desc\",\n        \"orderBy\": \"1\"\n      }\n    }\n  ],\n  \"listeners\": {}\n}","description":"","version":1,"kibanaSavedObjectMeta":{"searchSourceJSON":"{\n  \"index\": \"Metric-*\",\n  \"query\": {\n    \"query_string\": {\n      \"query\": \"*\",\n      \"analyze_wildcard\": true\n    }\n  },\n  \"filter\": []\n}"}}}

I beautified it

      {  
         "_index":".kibana",
         "_type":"visualization",
         "_id":"Metric_Status",
         "_score":0,
         "_source":{  
            "title":"Metric_Status",
            "visState":"{\"type\":\"histogram\",\"params\":{\"shareYAxis\":true,\"addTooltip\":true,\"addLegend\":true,\"mode\":\"stacked\",\"defaultYExtents\":false},\"aggs\":[{\"id\":\"1\",\"type\":\"count\",\"schema\":\"metric\",\"params\":{}},{\"id\":\"2\",\"type\":\"date_histogram\",\"schema\":\"segment\",\"params\":{\"field\":\"timeStamp\",\"interval\":\"auto\",\"min_doc_count\":1,\"extended_bounds\":{}}},{\"id\":\"3\",\"type\":\"terms\",\"schema\":\"group\",\"params\":{\"field\":\"Metric_RequestStateName.raw\",\"size\":5,\"order\":\"desc\",\"orderBy\":\"1\"}}],\"listeners\":{}}",
            "description":"",
            "version":1,
            "kibanaSavedObjectMeta":{  
               "searchSourceJSON":"{\"index\":\"efun-Metric-*\",\"query\":{\"query_string\":{\"query\":\"*\",\"analyze_wildcard\":true}},\"filter\":[]}"
            }
         }
      }\"schema\":\"group\",
      \n      \"params\":{  
         \n        \"field\":\"Metric_RequestStateName.raw\",
         \n        \"size\":5,
         \n        \"order\":\"desc\",
         \n        \"orderBy\":\"1\"\n
      }\n
      }\n
      ],
      \n  \"listeners\":{  

      }\n
      }","description":"",
      "version":1,
      "kibanaSavedObjectMeta":{  
      "searchSourceJSON":"{\n  \"index\": \"Metric-*\",\n  \"query\": {\n    \"query_string\": {\n      \"query\": \"*\",\n      \"analyze_wildcard\": true\n    }\n  },\n  \"filter\": []\n}"
      }
      }
      }

**Comment by gshively11** [comment]
I'm not sure what you mean by your first request.  Do you mean specifying in config exactly which document _ids you want to backup?

As for your second request, report+continue on error is definitely a good idea.  We don't want to break the backup because of one bad config.

I know beautifying things breaks elasticsearch-dump, so that's not supported at the moment.  I'd like to get that fixed at some point, but it will require a PR to their module.

Going to list this one as an enhancement for the 'continue on error' functionality.  And for now, don't beautify the files.

**Comment by gshively11** [comment]
Closing this one for now, tracking them in #10 and #11.
